# Generated by Django 2.2.2 on 2019-07-01 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('activity', models.CharField(max_length=80)),
                ('duration', models.IntegerField()),
                ('calories_burned', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_type', models.CharField(max_length=30)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=30)),
                ('age', models.DecimalField(decimal_places=0, max_digits=2)),
                ('activity_level', models.CharField(max_length=30)),
                ('calorie_intake_goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('calorie_output_goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('regular_exercises', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
