# Generated by Django 2.2.2 on 2019-06-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealburner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
