# Generated by Django 2.2.2 on 2019-07-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealburner_app', '0002_profile_fitness_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
